version: '3.8'

services:
  web:
    build: .
    container_name: yii1_web
    ports:
      - "8080:80"  # поменял на стандартный 8080
    volumes:
      - .:/var/www/html
      - ./protected/runtime:/var/www/html/protected/runtime
      - ./protected/data:/var/www/html/protected/data
      - ./assets:/var/www/html/assets
    working_dir: /var/www/html
    depends_on:
      - mysql
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - PHP_IDE_CONFIG=serverName=yii1

  mysql:
    image: mysql:8.0
    container_name: yii1_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: book_catalog
      MYSQL_USER: book_user
      MYSQL_PASSWORD: password123
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: yii1_phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8089:80"
    restart: always

volumes:
  mysql_data: